### ISSUE TITLE
Server description box in Settings can be resized

### ISSUE THREAD

**Issue by leafcutterant** [darkwallet/darkwallet#125]
Minor UI issue.

**Comment by sembrestels** [comment]
This can be fixed with CSS. The problem I see is that it can be resized horizontally, so we could set it to just resize it vertically or simply not resize.

``` css
textarea {
    resize: vertical | none;
}
```
